app: vjepa_2_1
nodes: 1
tasks_per_node: 1
cpus_per_task: 16
mem_per_gpu: 50G
folder: ./runs/vjepa_2_1/autodriving_future
data:
  dataset_type: VideoDataset
  datasets:
  - configs/train_2_1/vitg16/autodriving_train_paths.csv
  datasets_weights:
  - 1.0
  batch_size: 32
  # 8に変更
  crop_size: 256
  patch_size: 16

  # 【設定項目①】動画から切り出す全体の長さ（フレーム数）
  # 例: 16 にすると1回の学習で16フレーム分のクリップを扱います
  dataset_fpcs:
  - 16

  tubelet_size: 2
  fps: 4
  num_workers: 8
  persistent_workers: true
  pin_mem: true
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
loss:
  loss_exp: 1.0
  predict_all: true
  reg_coeff: 0.0
  shift_by_n: 0
  weight_distance_loss: true
  # 【設定項目③】損失計算に用いるフレームの範囲（開始と終了のインデックス）
  # 例えば 16フレームのうち最後の2フレーム（14フレーム目と15フレーム目）のみを使う場合:
  loss_target_frames: [12,15]


mask:
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: true
  max_keep: null

  # 【設定項目②】文脈（ヒント）として与える過去フレームの割合
  # 例えば dataset_fpcs が 16 でここを 0.75 にすると、
  # 16 × 0.75 = 最初の12フレーム が過去として与えられ、
  # 残り 16 - 12 = 4フレームが未来として予測されます。
  # もし「8フレーム見て8フレーム予測」ならここを 0.5 にします。
  max_temporal_keep: 0.75
  num_blocks: 1
  spatial_scale:
  - 0.0
  - 0.0
  # マスクする割合
  # 最小　最高
  temporal_scale:
  - 1.0
  - 1.0
  # full_complement が true のため、文脈以外の残り25%(4フレーム)がすべて未来予測のターゲットになる

meta:
  dtype: bfloat16
  eval_freq: 100
  load_checkpoint: true
  read_checkpoint: /home/thoth-22/kei_ws/vjepa2/runs/vjepa_2_1/autodriving_future/20260420_182802/best.pth.tar
  save_every_freq: 50
  seed: 239
  use_sdpa: true
model:
  use_decoder: true
  train_decoder_only: true
  has_cls_first: false
  img_temporal_dim_size: 1
  interpolate_rope: true
  is_causal: false
  lambda_value_img: 0.5
  lambda_value_vid: 0.5
  local_window:
  - -1
  - -1
  - -1
  modality_embedding: true
  model_name: vit_giant_xformers
  n_registers: 0
  n_registers_predictor: 0
  normalize_predictor: false
  pred_depth: 24
  pred_embed_dim: 384
  pred_is_causal: false
  pred_local_window:
  - -1
  - -1
  - -1
  pred_num_heads: 12
  uniform_power: true
  use_activation_checkpointing: true
  use_mask_tokens: true
  use_rope: true
  vit_conv: false
  zero_init_mask_tokens: true
optimization:
  ema:
  - 0.99925
  - 0.99925
  epochs: 50
  final_lr: 0.0012
  final_weight_decay: 0.04
  ipe: 300
  ipe_scale: 1.25
  lr: 0.0012
  start_lr: 0.0001
  warmup: 5
  #10
  weight_decay: 0.04
